#!/bin/sh

# Colors :
GREEN='\033[0;32m' # Green
BLUE='\033[1;36m'  # Blue
RED='\033[0;31m'   # Red
NC='\033[0m'       # No Color
SEPARATOR="echo"""

# Locale, hwclock, hostname
echo -e "${BLUE}Seting Up the Locale${NC}"
ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --systohc
echo 'pt_BR.UTF-8 UTF-8' >> /etc/locale.gen
locale-gen
echo 'LANG=pt_BR.UTF-8' >> /etc/locale.conf
echo -e "${BLUE}[+] Enter your Keyboard Layout: ${NC}"
read kb_layout
echo "KEYMAP=$kb_layout" >> /etc/vconsole.conf
echo "$kb_layout is set in /etc/vconsole.conf"
sleep 1
echo -e "${BLUE}[+] Enter The Hostname: ${NC}"
read host
echo $host >> /etc/hostname
echo "127.0.0.1       localhost" >> /etc/hosts
echo "::1             localhost" >> /etc/hosts
echo "$host is set as the hostname of the computer"
sleep 1
clear

# Pacman.conf
echo -e "${BLUE}Installing Essencial Packages${NC}"
sed -i "s/#Color/Color/" /etc/pacman.conf
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 5/" /etc/pacman.conf
sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
pacman -Sy --needed --noconfirm doas grub os-prober efibootmgr networkmanager libvirt fish xorg xorg-xinit
$SEPARATOR
echo -e "${GREEN}Installaling Base-devel Packages minus Sudo${NC}"
pacman -Sy --needed archlinux-keyring autoconf automake binutils bison debugedit fakeroot file findutils flex gawk gcc gettext grep groff gzip libtool m4 make pacman patch pkgconf sed texinfo which
echo -e "${GREEN}Installation Done${NC}"
clear

# User and Root Password
echo -e "${BLUE}Root Password${NC}"
passwd
echo -e "${BLUE}Create User${NC}"
echo -e "${BLUE}[+] User Name: ${NC}"
read username
useradd -m -G wheel,audio,video,optical,storage,libvirt -s /bin/fish $username
echo -e "${BLUE}$username Password${NC}"
passwd $username
echo 'permit keepenv persist :wheel' >> /etc/doas.conf
clear

# Grub with uefi
echo -e "${BLUE}Setting Up Grub With UEFI${NC}"
doas sed -i "s/^GRUB_TIMEOUT = 5/GRUB_TIMEOUT = 0/" /etc/default/grub
grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
grub-mkconfig -o /boot/grub/grub.cfg

# Enbling Services
echo -e "${BLUE}Enabling Services${NC}"
systemctl enable NetworkManager
systemctl enable bluetooth
systemctl enable libvirtd

# Reboot
echo -e "${GREEN}Press 'Control + d' and Reboot${NC}"
